### ISSUE TITLE
Consider using open command.

### ISSUE THREAD

**Issue by tarberd** [notquitedante/dotfiles#5]
https://github.com/danteissaias/dotfiles/blob/eac2edea67a611f560aa859fa6d8e26fa7b80177/files/.config/skhd/skhdrc#L2

Hey Dante, I was doodling with your config and got annoyed that wen using your script it would open two instances of iTerm at first. To solve that you could just use the `open` command with the *new* flag as flows: 
```
cmd - return : open -na iTerm
```  
Did you tried to use something like this before? I was having trouble finding how to execute iTerm and ended up at the manpages for `open`.

**Comment by danteissaias** [comment]
This is really cool. If you could go ahead and make a pull request I'll be happy to merge this.

**Comment by notquitedante** [comment]
I am no longer using SKHD, so I'm gonna go ahead and close this issue.
