### ISSUE TITLE
General Cleanup

### ISSUE THREAD

**Issue by notquitedante** [notquitedante/dotfiles#6]
There are a few reasons warranting this cleanup:
- There's a lot of stuff in this repository that's "hacky" and temperamental
- I want to have a more "lightweight" philisophy with minimal plugins etc.
- I have changed my application stack a significant amount since I last commited to this repository

Thus, I am ditching:
- Yabai
- SKHD
- Ranger
- NeoVim (in favour of Vim)

... and I am also overhauling my fish configuration.

**Comment by danteissaias** [comment]
This seems to be in the same spirit as what I am trying to achieve: https://github.com/cowboy/dotfiles so I'll probably end up using that architecture in this repo.
